# Generated by Django 3.1.4 on 2021-01-02 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210103_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 21, 41, 10, 864676, tzinfo=utc)),
        ),
    ]
