# Generated by Django 3.1.4 on 2021-01-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210103_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-time']},
        ),
    ]
