# Generated by Django 3.1.4 on 2021-01-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210103_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
