# Generated by Django 3.1.4 on 2021-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
