# Generated by Django 3.1.4 on 2021-01-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210109_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/profile_pics/default_profile_pic.png', null=True, upload_to='images/profile_pics'),
        ),
    ]
