# Generated by Django 3.1.4 on 2021-01-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210110_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
